[package]
name = "drift-gateway"
version = "1.5.5"
edition = "2024"

[dependencies]
actix-web = "*"
argh = "*"
drift-rs = { path = "../drift-rs", features = ["titan"] }
base64 = "0.22.1"
env_logger = "*"
faster-hex = "0.10.0"
futures-util = "*"
log = "*"
nanoid = "0.4.0"
reqwest = { version = "*", features = ["json"] }
rust_decimal = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sha256 = "1.6.0"
solana-account-decoder-client-types = "3"
solana-rpc-client-api = "3"
solana-sdk = "3"
solana-transaction-status = "3"
thiserror = "*"
tokio = {version ="*", features = ["full"]}
tokio-tungstenite = "*"

[profile.release]
panic = 'abort'
